# This is a basic workflow to help you get started with Actions

name: Deploy to Github Pages

# Controls when the action will run. 
on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Setup a node environment
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
      
      # Install dependencies
      - name: Install dependencies
        run: |
          npm ci

      # Build static frontend
      - name: Build Frontend
        run: |
          npm run generate
      
      # Deploy it
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
